// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_Fznu431GF2nivCSjTLlTy_UesELLHu8',
    appId: '1:726695923337:web:ca34a1f04218f6dbd18058',
    messagingSenderId: '726695923337',
    projectId: 'justchat-7b367',
    authDomain: 'justchat-7b367.firebaseapp.com',
    storageBucket: 'justchat-7b367.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8OwNKcq-BUfm9cI8wVNWqejnTwKHzyqs',
    appId: '1:726695923337:android:e9d8a1bf16904754d18058',
    messagingSenderId: '726695923337',
    projectId: 'justchat-7b367',
    storageBucket: 'justchat-7b367.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdz2NRluu6vBqvQoOYIGH0apTrudfyuHI',
    appId: '1:726695923337:ios:0f73ac6544e79f27d18058',
    messagingSenderId: '726695923337',
    projectId: 'justchat-7b367',
    storageBucket: 'justchat-7b367.appspot.com',
    iosBundleId: 'com.example.justChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdz2NRluu6vBqvQoOYIGH0apTrudfyuHI',
    appId: '1:726695923337:ios:3d0fa8c5a34a0be5d18058',
    messagingSenderId: '726695923337',
    projectId: 'justchat-7b367',
    storageBucket: 'justchat-7b367.appspot.com',
    iosBundleId: 'com.example.justChat.RunnerTests',
  );
}
